version: "3.9"

services:
  coursera_capstone:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coursera_capstone
    working_dir: /coursera_capstone
    volumes:
      - .:/coursera_capstone
    ports:
      - "8009:8000"
    command: tail -f /dev/null
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
